name: Build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build Site Artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Restore image cache
        uses: actions/cache@v4
        with:
          path: .image-cache
          key: images-${{ hashFiles('src/images/**/*') }}
          restore-keys: |
            images-

      - name: Build Site
        run: |
          npm ci
          npm run build

      - name: Upload site artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: _site
